final Map<String, String> tr = {
  'title': 'Bilgisayar Kontrolü',
  'enter_code': 'Bağlantı Kodunu Girin',
  'connect': 'Bağlan',
  'connected': 'Bağlandı',
  'device': 'Cihaz',
  'invalid_code': 'Geçersiz Kod',
  'take_screenshot': 'Ekran Görüntüsü Al',
  'shutdown_computer': 'Bilgisayarı Kapat',
  'settings': 'Ayarlar',
  'connection_duration': 'Bağlantı Süresi',
  'dark_mode': 'Karanlık Tema',
  'language': 'Dil',
  'disconnect': 'Bağlantıyı Kes',
  'about': 'Hakkında',
  'about_description': 'Bu uygulama uzaktan bilgisayar kontrolü sağlar.',
  'loading':'Yükleniyor..',
  'online': 'Çevrimiçi',
  'offline': 'Çevrimdışı',
  'last_update': 'Son Güncelleme',
  'memory': 'Hafıza',
  'screen_resolution': 'Ekran Çözünürlüğü',
  'disk_usage': 'Disk Kullanımı',
  'network_ip': 'Ağ IP',
  'mac_address': 'MAC',
  'last_screenshot': 'Son Görüntü',
  'shutdown': 'Kapat',
  'command_sent': 'Komut gönderildi',
  'task_list': 'Görev Listesi',
  'please_wait': 'İstek gönderildi, lütfen bekleyin...',
  'search_hint': 'İsme göre filtrele...',
  'cpu_sort': 'CPU\'ya göre',
  'memory_sort': 'RAM\'e göre',
  'no_sort': 'Sırasız',
  'kill_selected_processes': 'Seçilen Görevleri Sonlandır',
  'task_sent': 'İşlem gönderildi.',
  "enter_code_prompt": "Lütfen Bağlantı Kodunu Girin",
  "back": "Geri Dön",
  "welcome_text": "Silicore'a Hoşgeldin! \nKod hazırsa hadi başlayalım!",
  "continue_with_code": "KOD İLE DEVAM ET",
  "info_text":"Bilgisayarınızdaki kodla telefonunuzu bağlayın. Bağlantı gerçekleştikten sonra bilgisayardaki arayüz ilk kontrolden sonra kapanacaktır. Bağlantıyı kestiğinizde arayüz tekrar kendiliğinden açılır.",
  "error_text":"Kod geçersiz!",
  "success_delete_photo":"Fotoğraf başarıyla silindi!",
  "error_delete_photo":"Silme işlemi sırasında bir hata oluştu."
};
