final Map<String, String> en = {
  'title': 'Computer Control',
  'enter_code': 'Enter Connection Code',
  'connect': 'Connect',
  'connected': 'Connected',
  'device': 'Device',
  'invalid_code': 'Invalid Code',
  'take_screenshot': 'Take Screenshot',
  'shutdown_computer': 'Shutdown Computer',
  'settings': 'Settings',
  'connection_duration': 'Connection Duration',
  'dark_mode': 'Dark Mode',
  'language': 'Language',
  'disconnect': 'Disconnect',
  'about': 'About',
  'about_description': 'This app provides remote computer control.',
  'loading':'Loading..',
  'online': 'Online',
  'offline': 'Offline',
  'last_update': 'Last Update',
  'memory': 'Storage',
  'screen_resolution': 'Screen Resolution',
  'disk_usage': 'Disk Usage',
  'network_ip': 'Network IP',
  'mac_address': 'MAC',
  'last_screenshot': 'Last Screenshot',
  'shutdown': 'Shutdown',
  'command_sent': 'Command sent',
  'task_list': 'Task List',
  'please_wait': 'Request sent, please wait...',
  'search_hint': 'Filter by name...',
  'cpu_sort': 'By CPU',
  'memory_sort': 'By RAM',
  'no_sort': 'None',
  'kill_selected_processes': 'Kill Selected Processes',
  'task_sent': 'Task sent.',
  "enter_code_prompt": "Please Enter the Connection Code",
  "back": "Go Back",
  "welcome_text": "Welcome to Silicore! \nIf the code is ready, let's started!",
  "continue_with_code": "CONTINUE WITH CODE",
  "info_text":"Connect your phone with the code on your computer. After the connection is made, the interface on the computer will close after the first check. When you disconnect, the interface will open again automatically.",
  "error_text":"Code is invalid!",
  "success_delete_photo":"Photo deleted successfully!",
  "error_delete_photo":"An error occurred during the deletion process."
};
